# Add your DeepInfra API key below
#DEEPINFRA_API_KEY = "gKr49paqDcNGsPDFVOl2X2Xyr0yJGAd9"

# Add your Cohere API key below
#COHERE_API_KEY = "Qdgwxr3exxIDkPHjB4RqXfo5kvDJGarNO2aulKaW"
MISTRAL_API_KEY = "sBkfECSPd1qh1Y4qNRdiPPjovaNASJ41"
